from turtle import Turtle, Screen
import time
import random

MOVE_LENGTH = 20
UP = 90
DOWN = 270
LEFT = 180
RIGHT = 0
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
RACKET_DISTANCE_FROM_WALL = 50
RACKET_SIZE = 5
RACKET_WIDTH_SIZE = 20
RACKET_LENGTH = RACKET_SIZE * RACKET_WIDTH_SIZE
GAME_END_TIMER = 10000
INITIAL_BALL_SPEED = 0.075
BALL_SPEED_CHANGE_STEP = 0.9
